/*********************************************************************************************
 * Name      : Milan Bui
 * Date      : 29 April 2022
 * Class     : CS 4310.01
 * Assignment: Project 2 - Task #2
 *      Your program will service a disk with 5,000 cylinders numbered 0 to 4,999. The program 
 *      will be passed the initial position of the disk head (as a parameter on the command 
 *      line) and report the total amount of head movement and total number of change of 
 *      direction required by each algorithm under each of the following cases:
 *      > a. The program will generate a random series of 1,000 cylinder requests and service 
 *           them according to each of the algorithms listed above.
 *      > b. The program will read a series of cylinder requests from an input.txt file and 
 *           service them according to each of the algorithms listed above.
 ********************************************************************************************/
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;
import java.util.Random;


public class Main {
	public static void main(String[] args) {
		
		// VARIABLES
		final int NUM_OF_CYLINDERS = 5000;                  // number of cylinders
		final int HEAD_POSITION = Integer.valueOf(args[0]); // current head position
		final int PREV_POSITION = Integer.valueOf(args[1]); // previous position
		int[] fcfsResult;   // FCFS - total head movements and total direction change
		int[] sstfResult;   // SSTF - total head movements and total direction change
		int[] scanResult;   // SCAN - total head movements and total direction change
		int[] cscanResult;  // C-SCAN - total head movements and total direction change
		int selection;      // User selection for request input
		int fileNumber = 1; // number to use in file name generated by option 1
		ArrayList<Integer> requests = new ArrayList<Integer>(); // List of requests
		Scanner userIn = new Scanner(System.in);                // User input stream
		
		// Displays program header
		System.out.print(String.format("%40s", "-").replace(' ', '-'));
		System.out.print("TASK #2");
		System.out.println(String.format("%40s", "-").replace(' ', '-'));
		System.out.println();
		
		// Displays starting values
		System.out.println(NUM_OF_CYLINDERS + " cylinders");
		System.out.println("Current head position : " + HEAD_POSITION);
		System.out.println("Previous head position: " + PREV_POSITION);
		
		try {
			do {
				// Displays menu and prompts user for selections
				System.out.println();
				System.out.println("How would you like to do?");
				System.out.println("1. Generate 1000 randomized requests");
				System.out.println("2. Read requests from input file");
				System.out.println("3. Exit");
				System.out.print("Enter selection: ");
				selection = userIn.nextInt();
				System.out.println();
				
				// If selection is 1 or 2
				if (selection == 1 || selection == 2) {
					
					// If selected to generate random numbers
					if (selection == 1) {
						
						// Creates file to output randomized numbers
						String fileName = "RandomizedRequests" + fileNumber + ".txt";
						File randomFile = new File(fileName);
						randomFile.createNewFile();
						FileWriter writer = new FileWriter(fileName);
					      
						Random rand = new Random();
						requests = new ArrayList<Integer>();

						// Generates 1000 random numbers between 0 and NUM_OF_CYLINDERS
						// Adds to request list and file
						for (int i = 0; i < 1000; i++) {

							int num = rand.nextInt(NUM_OF_CYLINDERS);
							requests.add(num);
							writer.write(String.format("%-6d", i) + "| " 
							             + Integer.toString(num) + "\n");
						}
						
						writer.close();
						fileNumber++;

					} else if (selection == 2) {

						// Prompts user for path to input file
						String filePath;
						System.out.print("Enter full path to input file: ");
						userIn.nextLine();
						filePath = userIn.nextLine();

						// Create file input stream
						File inputFile = new File(filePath);
						Scanner fileIn = new Scanner(inputFile);
						
						requests = new ArrayList<Integer>();

						// While has not reached the end of file, add requests to list
						while (fileIn.hasNext()) {

							String line = fileIn.nextLine();
							int num = Integer.valueOf(line);
							requests.add(num);

						}
						
						fileIn.close();
					}

					// Creates scheduling alg object to process requests
					SchedulingAlgorithms disk = new SchedulingAlgorithms(HEAD_POSITION, 
							                                             PREV_POSITION, 
							                                             NUM_OF_CYLINDERS,
							                                             requests);

					// Processes requests using each algorithm
					fcfsResult = disk.fcfs();
					sstfResult = disk.sstf();
					scanResult = disk.scan();
					cscanResult = disk.cscan();
					
					// OUTPUT - displays results in a table
					System.out.println();
					System.out.print(String.format("%-12s", "Algorithm"));
					System.out.print(String.format("%-23s", "Total Head Movements"));
					System.out.print(String.format("%-30s", "Total Direction Changes"));
					System.out.println();
					System.out.println(String.format("%-65s", "-").replace(' ', '-'));

					System.out.print(String.format("%-12s", "FCFS"));
					System.out.print(String.format("%-25d", fcfsResult[0]));
					System.out.println(String.format("%-30s", fcfsResult[1]));

					System.out.print(String.format("%-12s", "SSTF"));
					System.out.print(String.format("%-25d", sstfResult[0]));
					System.out.println(String.format("%-30s", sstfResult[1]));

					System.out.print(String.format("%-12s", "SCAN"));
					System.out.print(String.format("%-25d", scanResult[0]));
					System.out.println(String.format("%-30s", scanResult[1]));

					System.out.print(String.format("%-12s", "C-SCAN"));
					System.out.print(String.format("%-25d", cscanResult[0]));
					System.out.println(String.format("%-30s", cscanResult[1]));
					System.out.println();
					
				} 
				// If user selected to exit, terminate
				else if (selection == 3){
					System.out.println("Program Terminated");
				}
				// If input is invalid
				else {
					System.out.println("Invalid selection");
				}
			} while(selection != 3);
			
			userIn.close();
			
		} catch(InputMismatchException e) {  // input type doesnt match
			System.err.println("Invalid Input | " + e.getClass());
		}
		catch (NumberFormatException e) {  // cannot convert number
			
			System.err.println(e.getMessage());
			
		} catch (FileNotFoundException e) { 
			
			System.err.println("FILE NOT FOUND | " + e.getMessage());
			
		} catch (Exception e) {
			System.err.println(e.getMessage() + "\n" + e.getCause() + "\n" 
					+ e.getStackTrace());
			e.printStackTrace();
		}
		
	}
}
